SUBDIR= 	overview
SUBDIR+=	process
SUBDIR+=	memory
SUBDIR+=	storage
#SUBDIR+=	distributed
#SUBDIR+= 	vm

INCLUDE_MIUNTEX=../miuntex
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
